# Site settings
title: Mayday 2.0
email: info@mayday.us
description: > # this means to ignore newlines until "baseurl:"
  Mayday 2.0
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mayday.us" # the base hostname & protocol for your site
twitter_username: MAYDAYUS
github_username:  MayOneUS


# Build settings
markdown: kramdown
